// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table Raw_Bike (BikepointID:string, Street:string, Neighbourhood:string, Latitude:real, Longitude:real, No_Bikes:int, No_Empty_Docks:int) 
.create-or-alter table Raw_Bike ingestion json mapping 'Raw_Bike_mapping'
```
[{"Properties":{"Path":"$['BikepointID']"},"column":"BikepointID","datatype":""},{"Properties":{"Path":"$['Street']"},"column":"Street","datatype":""},{"Properties":{"Path":"$['Neighbourhood']"},"column":"Neighbourhood","datatype":""},{"Properties":{"Path":"$['Latitude']"},"column":"Latitude","datatype":""},{"Properties":{"Path":"$['Longitude']"},"column":"Longitude","datatype":""},{"Properties":{"Path":"$['No_Bikes']"},"column":"No_Bikes","datatype":""},{"Properties":{"Path":"$['No_Empty_Docks']"},"column":"No_Empty_Docks","datatype":""}]
```
.create-merge table ExamScores (student_id:guid, exam_score:int, exam_code:string) 
.create-or-alter function with (docstring = "Gets all datapoints for a given BikepointID", skipvalidation = "true") GetBikeDataByID(ID:string) {
    Raw_Bike
    | where BikepointID == ID
 }
.create-or-alter materialized-view  BikeAvailabilityByNeighborhood on table Raw_Bike { Raw_Bike
    | summarize
        MinBikes = min(No_Bikes),
        MaxEmptyDocks = max(No_Empty_Docks)
        by BikepointID }
